services:
  rest_api_pg:
    container_name: rest_api_pg
    image: postgres:17.6
    restart: always
    volumes:
      - rest_pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-Abcd@1234}
      POSTGRES_DB: ${PG_DB:-rest}
    ports:
      - "5432:5432"
    networks:
      - rest_api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rest_api_redis:
    container_name: rest_api_redis
    image: redis:7-alpine
    restart: always
    volumes:
      - rest_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - rest_api_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rest_pg_data:
  rest_redis_data:

networks:
  rest_api_network:
    driver: bridge
