services:
  dr_rest_app:
    container_name: dr_rest_app
    image: drglasdou/dr_rest_app:latest
    build:
      context: .
      dockerfile: dockerfile.prod
    restart: always
    env_file:
      - .env
    environment:
      PG_HOST: dr_rest_pg
      REDIS_HOST: dr_rest_redis
    ports:
      - "4000:4000"
    depends_on:
      dr_rest_app_pg:
        condition: service_healthy
    networks:
      - dr_rest_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
