services:
  dr_rest_pg:
    container_name: dr_rest_pg
    image: postgres:18-alpine
    restart: always
    volumes:
      - dr_rest_pg_data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-Abcd@1234}
      POSTGRES_DB: ${PG_DB:-rest}
    ports:
      - "5432:5432"
    networks:
      - dr_rest_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  dr_rest_redis:
    container_name: dr_rest_redis
    image: redis:7-alpine
    restart: always
    volumes:
      - dr_rest_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - dr_rest_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dr_rest_pg_data:
  dr_rest_redis_data:

networks:
  dr_rest_network:
    driver: bridge
