minimumReleaseAge: 1440
packages:
  - '.'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - lefthook
  - prisma
  - unrs-resolver

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  lefthook: true
  prisma: true
  unrs-resolver: true
